### ISSUE TITLE
path配置的加上日期模板

### ISSUE THREAD

**Issue by tianfeng98** [tuot/picgo-plugin-gitea#1]
path使用日期配置，例如：path为`YYYY-MM-DD`时，上传目录文件所属目录为当天日期。
使用日期配置便于图床文件的分类，需要查找时更方便。
![image](https://user-images.githubusercontent.com/37977609/171842118-96dbcfb1-e674-4b41-8bd5-d94b74c08912.png)

**Comment by tuot** [comment]
Supported, please update it.
